# Generated by Django 3.2.8 on 2021-10-22 06:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('7cbf1d12-7166-4c3a-b1d2-aeea45fc6dc9'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(choices=[], max_length=50, null=True)),
                ('issue_to_user', models.CharField(choices=[], max_length=50, null=True)),
                ('issue_from', models.DateTimeField(null=True)),
                ('issue_to', models.DateTimeField(null=True)),
                ('published_date', models.DateTimeField()),
                ('price', models.FloatField(default=0.0)),
                ('penalty', models.IntegerField(default=0)),
            ],
        ),
    ]
