# Generated by Django 3.2.8 on 2021-10-24 09:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_auto_20211022_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(choices=[('admin@gmail.com', 'admin@gmail.com'), ('kumar1243@gmail.com', 'kumar1243@gmail.com'), ('kumar1243@gmail.com', 'kumar1243@gmail.com')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d85ce6f6-5da2-47e4-bcf3-fd02c57829c1'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='issue_to_user',
            field=models.CharField(choices=[('narendrakush@gmail.com', 'narendrakush@gmail.com')], max_length=50, null=True),
        ),
    ]
