# Generated by Django 3.2.8 on 2021-10-22 06:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 6, 31, 36, 735616, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user1',
            name='id',
            field=models.UUIDField(default=uuid.UUID('436db1b6-506c-4f28-bb28-175620fdacfa'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user1',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 6, 31, 36, 735631, tzinfo=utc)),
        ),
    ]
