# Generated by Django 3.2.8 on 2021-10-22 08:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0002_auto_20211022_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 8, 24, 6, 878600, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user1',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7662145d-e8ef-4b93-a0e9-4626145220c3'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user1',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user1',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 8, 24, 6, 878616, tzinfo=utc)),
        ),
    ]
