# Generated by Django 3.2.8 on 2021-10-24 09:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0003_auto_20211022_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 24, 9, 51, 31, 321025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user1',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5e2fa752-bbf7-43e6-b59b-cea9f80103bc'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user1',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 24, 9, 51, 31, 321038, tzinfo=utc)),
        ),
    ]
